### ISSUE TITLE
Why re-export faker

### ISSUE THREAD

**Issue by texastoland** [snaplet/copycat#43]
I stumbled on this from the Snaplet docs. Just curious why re-export a non-dependency? I was expecting copycat to provide a deterministic or generate language files.

**Comment by justinvdm** [comment]
Hey @texastoland, good question.

Short answer - historical reasons :)

Long answer:
We used to depend on faker - to make use of the underlying datasets that faker provides (e.g. names, surnames, cities, etc). IIRC, at the time we thought we'd provide faker as a re-export in case people needed to reach for it instead of copycat for some particular use case. For example, to build something out of copycat's primitives, but use data from faker. Granted, all that is possible without a re-export (people could just depend on faker directly for that case), but regardless that was what we decided at the time.

Then recently we decided to stop depending on it. Step 1 was to not use it under the hood anymore (this is done). Step 2 is to remove the re-export, but we still need to get to this.

Hope that helps and make's sense!

**Comment by texastoland** [comment]
That's what I assumed thanks! How did you decide not to depend on their locale files? Naively it seems like win/win for this project's goals.

**Comment by justinvdm** [comment]
> That's what I assumed thanks! How did you decide not to depend on their locale files? Naively it seems like win/win for this project's goals.

Also a good question. We were finding that when upgrading faker, the data would change, which would cause breaking changes for copycat (the same input would map to a different output now that the data changed). This breaks the determinism people are likely relying on copycat for. It's a tricky one, because the data needs to change for it to be improved. But maintaining the data ourselves it gives us more control over this.
