### ISSUE TITLE
When upgrading from `0.17.3` to `0.18.1`, the values generated are different, deterministic but different from before

### ISSUE THREAD

**Issue by Jolg42** [snaplet/copycat#49]
This looks like a breaking change in the deterministic behavior, in comparison to previous versions.

See https://github.com/prisma/prisma/pull/21718

Example test failing
https://github.com/prisma/prisma/actions/runs/6726544886/job/18283002179?pr=21718#step:8:2012
```
FAIL 0-legacy-ports/aggregate-raw/tests.ts
  ● 0-legacy-ports.aggregate-raw (provider=mongodb) › match

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `0-legacy-ports.aggregate-raw (provider=mongodb) match 1`

    - Snapshot  - 2
    + Received  + 2

      [
        {
    -     email: Kyla_Beer587@fraternise-assassination.name,
    +     email: Kyla_Crist96556@cancollaboration.biz,
        },
        {
    -     email: Arielle.Reichel85426@hunker-string.org,
    +     email: Arielle.Oberbrunner94321@fulljuggernaut.org,
        },
      ]

      70 |       })
      71 |
    > 72 |       expect(users).toMatchInlineSnapshot(`
         |                     ^
      73 |         [
      74 |           {
      75 |             email: Kyla_Beer587@fraternise-assassination.name,

      at Object.<anonymous> (0-legacy-ports/aggregate-raw/tests.ts:72:21)
```

- How can I ensure that this never happens again? Could I use a seed for example?
- Is it possible to somehow get back the old deterministic behavior?

**Comment by justinvdm** [comment]
Hey @Jolg42 

Yep, this was indeed a breaking change. And I'm sorry, we did not communicate this well (to your points in #47 and #48). 

> How can I ensure that this never happens again? Could I use a seed for example?

It's a tricky one - the reason for the breaking change was because of improvements made. Some improvements we make can be done in a way that does not change the current output for a given input, but some changes are unfortunately not this way. I know how annoying this is, considering the whole point of copycat is that the outputs do not change if the inputs do not.

I think the best we can do is this:
* Actually have a changelog
* Use major version bumps rather than minor for breaking changes like this

> Is it possible to somehow get back the old deterministic behavior?

Copycat should still be deterministic, in that a given input will map to a given output. If this is no longer the case, that is a bug we should investigate. After upgrading copycat, the same input will now map to a different output (because of the breaking change), but it'll always map to this new output (e.g. when called with the same input multiple times).

That said, I think you're referring more to the fact that the output is now different, and you want it to be the old output, right?  In that case, if you need to get back to the old output, you can downgrade to [0.18.0-rc.6](https://www.npmjs.com/package/@snaplet/copycat/v/0.18.0-rc.6) or earlier. That would be a temporary fix until you are ready to upgrade though. If you need it to say the same output but still get the improvements that `0.18.1` adds, I'm afraid that isn't possible because of the nature of the improvements.

Does that make sense?

**Comment by Jolg42** [comment]
Thanks, @justinvdm 🙌🏼. Peter mentioned to me last night that there was maybe another option, but he was not sure about that, so I thought it was better to ask!

For now, we'll keep the old version until we have capacity to upgrade, it's not a priority compared to other things at the moment. We'll get to it one day 👍🏼

**Comment by justinvdm** [comment]
@Jolg42 release notes for `0.18.1`, as promised :) https://github.com/snaplet/copycat/releases/tag/v0.18.1

We'll continue to do this for new releases.

**Comment by Jolg42** [comment]
Very nice release notes & performance improvement 🙌🏼 Well done!
